/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatRecordItem: typeof import('./src/components/ChatRecordItem.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarDivider: typeof import('@varlet/ui')['_DividerComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarMenu: typeof import('@varlet/ui')['_MenuComponent']
    VarPaper: typeof import('@varlet/ui')['_PaperComponent']
  }
}
